config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  post "top/new", as: "shops", to: "shops#index", path: "shops"
  resources :shops, except: [:new, :create, :edit]

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :shop
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :item
  has_one :shop_detail
  geocoded_by :address
  after_validation :geocode
  attr_accessor :conditions_categorys, :area

  def filter_category
    @shop_ids = []
    set_shop_ids
    @shop_ids.uniq!
  end

  def filter_area
    if @area.present?
      hit_shops = Shop.where("address like ?", "%#{@area}%")
      hit_shop_ids = hit_shops.map{|hit_shop| hit_shop.id}
      @shop_ids = @shop_ids & hit_shop_ids
    end
  end

  def set_matching_shops
    @shops = []
    @shop_ids.each do |id|
      @shops << Shop.find_by(id: id)
    end
    return @shops
  end

  def set_params(params)
    @conditions_categorys = params[:top][:category]
    @area = params[:top][:area]
  end

  def get_markers(shops)
    hash = Gmaps4rails.build_markers(shops) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow shop.name
      marker.json({name: shop.name})
    end
    return hash
  end

  def self.get_shop_pictures_path(obj)
    path = obj.image_path + "/" + "*"
    shop_images = []
    dirs = Dir.glob("**/"+path)
    dirs.each do |d|
      d.slice!("app")
      d.slice!("images/")
      shop_images << d
    end
    return shop_images
  end

  private
  def matching_shops_ids(category)
    @hit_shops.each do |shop|
      shop_category = shop.category.split(",")
      shop_category.map!(&:strip)
      shop_category.map{ |str|
        @shop_ids << shop.id if str == category
      }
    end
  end

  def set_shop_ids
    if @conditions_categorys.nil?
      @conditions_categorys = ["未選択"]
      Shop.all.map{|shop| @shop_ids << shop.id}
    else
      @conditions_categorys.each do |category|
        @hit_shops = Shop.where("category like ?", "%#{category}%")
        matching_shops_ids(category)
      end
    end
  end
  
end

app/models/shop_detail.rb
class ShopDetail < ActiveRecord::Base
  belongs_to :shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :update, :destroy]
  before_action :permit_params, only: [:index]
  before_action :check_conditions, only: [:index]
  before_action :set_params, only: [:index]
  # GET /shops
  # GET /shops.json
  def index
    conditions_filter
    @shops.filter_area
    @found_shops = @shops.set_matching_shops
    @message = "条件に合うお店がありませんでした" if @found_shops.empty?
    @hash = @shops.get_markers(@found_shops)
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_shop
    @shop = Shop.find(params[:id])
    @hash = Shop.new.get_markers(@shop)
  end

  def set_params
    @shops = Shop.new
    @shops.set_params(params)
  end

  def check_conditions
    redirect_to(root_path) if !params[:top].include?(:category)
  end

  def conditions_filter
    @shops.filter_category
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def permit_params
    params.require(:top).permit(:category, :area)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width; initial-scale=1.0" />
  <title>GiftTo</title>
  <%= favicon_link_tag '/assets/favicon.ico' %>
  <% if request.from_smartphone? %>
    <%= stylesheet_link_tag 'normalize' %>
    <%= stylesheet_link_tag 'inside/mobile' %>
    <%= stylesheet_link_tag 'inside/flickity.min' %>
    <!-- <%= stylesheet_link_tag 'inside/sliderMobile' %>
    <%= stylesheet_link_tag 'inside/sliderMobileInterior' %> -->
  <% else %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <% end %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <header name="top">
    <%= link_to image_tag("logo.png", class: 'logo', alt: 'ロゴ', width: '222', height:'95'), root_path %>
  </header>

  <%= yield %>

  <footer>
    <% if !request.from_smartphone? %>
      <a href="#top">▲ページTOPへ</a>
    <% end %>
    <small>北九州市立大学<br>Chevalier.pop</small>
  </footer>

</body>
</html>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br>
    <%= f.text_field :image_path %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :store_hours %><br>
    <%= f.text_field :store_hours %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :situation %><br>
    <%= f.text_field :situation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/_goodsList.html.erb
<ul id="goods">
  <% @shop.item.all.each do |item| %>
    <li><a href=<%= item.image_path %> target="_blank" class="lb"><img class="goodsImage" src=<%= item.image_path %> width="200" height="200" alt="商品の写真"></a>
      <p><font size="-1">材質：<%= item.material %></font></p>
      <p><font size="-1">¥<%= item.price %></font></p>
    </li>
  <% end %>
</ul>

app/views/shops/_goodsListMobile.html.erb
<!-- <div id="slider">
  <div class="slideFrame">
    <div class="slideSet">
      <% @shop.item.all.each do |item| %>
        <div class="slide"><img class="goodsImage" src=<%= item.image_path %> width="320" height="200" alt="商品の写真"></div>
      <% end %>
    </div>
  </div>
</div> -->

<div class="main-gallery">
  <% @shop.item.all.each do |item| %>
    <div class="gallery-cell">
      <img class="goodsImage" src=<%= item.image_path %> width="320" height="200" alt="商品の写真">
      <p style="margin-left: 5%;">材質：<%= item.material %></p>
      <p style="margin-left: 5%;">¥<%= item.price %></p>
    </div>
  <% end %>
</div>

app/views/shops/_searchResult.html.erb
<div id="main">
  <div class="inner">
    <section id="research">
      <div id="searchConditions">
        <h2 class="formTitle">検索条件</h2>
        <dl>
          <dt>ジャンル</dt>
          <dd>：<%= @shops.conditions_categorys.join(",") %></dd>

          <dt>地域</dt>
          <dd>：<%= @shops.area %></dd>
        </dl>
      </div>
      <%= render :partial => "topForm" %>
    </section>

    <section id="searchResult">
      <% if @message.present? %>
        <h1><%= @message %></h1>
      <% else %>
        <div id="map">
          <div id="map_canvas"></div>
        </div>

        <div id="shopList">
          <h4><%= @found_shops.length %>件ヒット</h4>
          <div id="shopListInner">
            <ul>
              <% @found_shops.each do |shop| %>
                <li>
                  <div id="shop">
                    <%= link_to shop_path(shop.id), target: "_blank" do %>
                      <img src = <%= Shop.get_shop_pictures_path(shop)[0] %> alt="お店の画像"/>
                      <div id="shopName">
                        <h2><%= shop.name %></h2>
                        <p><span>住所：</span><%= shop.address %></p><br>
                        <p class="characteristic"><%= shop.characteristic %></p>
                      </div>
                    <% end %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </section>
  </div>
</div>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map_canvas'}}, function(){
  if(<%= @shops.area.empty? %>){
    if(navigator.geolocation)
      navigator.geolocation.getCurrentPosition(displayOnMap);
  };
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    picture: {
        url: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=現|00F0F0|000000',
        width:  36,
        height: 36
      },
    infowindow: "現在地",
  });
  handler.map.centerOn(marker);
};
</script>

app/views/shops/_searchResultMobile.html.erb
<div id="main">
  <div id="research">
    <div id="searchConditions">
      <h4 class="formTitle">検索条件</h4>
      <dl>
        <dt>ジャンル</dt>
        <dd>：<%= @shops.conditions_categorys.join(",") %></dd>

        <dt>地域</dt>
        <dd>：<%= @shops.area %></dd>
      </dl>
    </div>
    <%= render :partial => "topFormMobile" %>
  </div>

  <% if @message.present? %>
    <h1><%= @message %></h1>
  <% else %>
    <div id="shopList">
      <h4><%= @found_shops.length %>件ヒット</h4>
      <div id="shopListInner">
        <ul>
          <% @found_shops.each do |shop| %>
            <li>
              <div id="shop">
                <%= link_to shop_path(shop.id) do %>
                  <img src = <%= Shop.get_shop_pictures_path(shop)[0] %> alt="お店の画像"/>
                  <div id="shopName">
                    <h2><%= shop.name %></h2>
                    <p><span>住所：</span><%= shop.address %></p>
                    <p class="characteristic"><%= shop.characteristic %></p>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div id="map">
      <div id="map_canvas"></div>
    </div>
    <div id="mapLink">
      <a href="#map">地図を見る</a>
    </div>
  <% end %>
</div>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map_canvas'}}, function(){
  if(<%= @shops.area.empty? %>){
    if(navigator.geolocation)
      navigator.geolocation.getCurrentPosition(displayOnMap);
  };
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    picture: {
        url: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=現|00F0F0|000000',
        width:  36,
        height: 36
      },
    infowindow: "現在地",
  });
  handler.map.centerOn(marker);
};

$("#accordion").click(function(){
  $(".unit > .researchFormMobile").slideToggle();
  $(".formTitle span").toggleClass("active");
});
</script>

app/views/shops/_shopInfo.html.erb
<h1><%= @shop.name %></h1>
<div id="shopInfo">
  <table>
    <tr>
      <td>住所</td>
      <td><%= @shop.address %></td>
    </tr>

    <tr>
      <td>TEL</td>
      <td><%= @shop.shop_detail.tel %></td>
    </tr>

    <tr>
      <td>営業時間</td>
      <td><%= @shop.shop_detail.store_hours %></td>
    </tr>

    <tr>
      <td>休業日</td>
      <td><%= @shop.shop_detail.holiday %></td>
    </tr>

    <tr>
      <td>URL</td>
      <td><a href=<%= @shop.shop_detail.web %> target="_blank" class="shopURL"><%= @shop.shop_detail.web %></a></td>
    </tr>

    <tr>
      <td>アクセス</td>
      <td><%= @shop.shop_detail.station %></td>
    </tr>

    <div id="slider">
      <div class="slideFrame">
        <div class="slideSet">
          <% Shop.get_shop_pictures_path(@shop).each do |image| %>
            <div class="slide"><img src=<%= image %> width="500" height="200" alt="お店の内装"></div>
          <% end %>
        </div>
      </div>
    </div>

    <!-- <img src = <%= @shop.image_path %>/> -->
  </table>
</div>

<div class="abstract">
  <dl>
    <dt>概要</dt>
    <dd><%= simple_format(@shop.shop_detail.abstract) %></dd>
  </dl>
</div>

<h3 id="goodsLink">商品画像<a href="#accessLink" class="pageLink">▼アクセスへ</a></h3>
<% if request.from_smartphone? %>
  <%= render :partial => "goodsListMobile" %>
<% else %>
  <%= render :partial => "goodsList" %>
<% end %>

<h3 id="accessLink">アクセス<a href="#goodsLink" class="pageLink">▲商品画像へ</a></h3>
<div id="access">
  <p>アクセス : <%= @shop.shop_detail.station %></p>
  <div id="access_canvas"></div>
</div>
<%= javascript_include_tag 'slider' %>

app/views/shops/_topForm.html.erb
<%= form_for "top", :url => shops_path do |f| %>
  <h2 class="formTitle">再検索条件の入力</h2>
  <h5 class="formLabel"><%= f.label "買いたいものを選択してください" %><span class="areaWarning">*必須</span></h5>
  <dl id="categoryList">
    <!-- <dt><%= f.label "ファッション" %></dt> -->
    <dd>
      <li><%= f.check_box :category, {id: "top_check1", class: "checkBox", multiple: true}, "ネックレス", nil %><%= f.label 'check1', "ネックレス" %></li>
      <li><%= f.check_box :category, {id: "top_check5", class: "checkBox", multiple: true}, "ペンダント", nil %><%= f.label 'check5', "ペンダント" %></li>
      <li><%= f.check_box :category, {id: "top_check3", class: "checkBox", multiple: true}, "ブレスレット", nil %><%= f.label 'check3', "ブレスレット" %></li>
      <li><%= f.check_box :category, {id: "top_check4", class: "checkBox", multiple: true}, "指輪", nil %><%= f.label 'check4', "指輪" %></li>
      <li><%= f.check_box :category, {id: "top_check10", class: "checkBox", multiple: true}, "イヤリング", nil %><%= f.label 'check10', "イヤリング" %></li>
      <li><%= f.check_box :category, {id: "top_check14", class: "checkBox", multiple: true}, "ピアス", nil %><%= f.label 'check14', "ピアス" %></li>
      <li><%= f.check_box :category, {id: "top_check7", class: "checkBox", multiple: true}, "ブローチ", nil %><%= f.label 'check7', "ブローチ" %></li>
      <li><%= f.check_box :category, {id: "top_check9", class: "checkBox", multiple: true}, "バッグ", nil %><%= f.label 'check9', "バッグ" %></li>
      <li><%= f.check_box :category, {id: "top_check11", class: "checkBox", multiple: true}, "ポーチ", nil %><%= f.label 'check11', "ポーチ" %></li>
      <li><%= f.check_box :category, {id: "top_check2", class: "checkBox", multiple: true}, "財布", nil %><%= f.label 'check2', "財布" %></li>
      <li><%= f.check_box :category, {id: "top_check6", class: "checkBox", multiple: true}, "腕時計", nil %><%= f.label 'check6', "腕時計" %></li>
      <li><%= f.check_box :category, {id: "top_check13", class: "checkBox", multiple: true}, "雑貨", nil %><%= f.label 'check13', "雑貨" %></li>
    </dd>
  </dl>

  <h5 class="formLabel"><%= f.label "地域を入力してください" %></h5>
  <div id="textField"><%= f.text_field :area, :class => 'textField', :placeholder => "例）福岡市"%></div>
  <p class="areaWarning">※未入力の場合，現在地から検索します</p>
  <%= f.submit 'お店を再検索', :class => 'submitBtn'%>
<% end %>

app/views/shops/_topFormMobile.html.erb
<%= form_for "top", :url => shops_path do |f| %>
  <h4 id="accordion" class="formTitle"><span>再検索条件の入力</span></h4>
  <div class="unit">
    <div class="researchFormMobile">
      <h5 class="formLabel"><%= f.label "買いたいものを選択してください" %><span class="areaWarning">*必須</span></h5>
      <dl id="categoryList">
        <!-- <dt><%= f.label "ファッション" %></dt> -->
        <dd>
          <li><%= f.check_box :category, {id: "top_check1", class: "checkBox", multiple: true}, "ネックレス", nil %><%= f.label 'check1', "ネックレス" %></li>
          <li><%= f.check_box :category, {id: "top_check5", class: "checkBox", multiple: true}, "ペンダント", nil %><%= f.label 'check5', "ペンダント" %></li>
          <li><%= f.check_box :category, {id: "top_check3", class: "checkBox", multiple: true}, "ブレスレット", nil %><%= f.label 'check3', "ブレスレット" %></li>
          <li><%= f.check_box :category, {id: "top_check4", class: "checkBox", multiple: true}, "指輪", nil %><%= f.label 'check4', "指輪" %></li>
          <li><%= f.check_box :category, {id: "top_check10", class: "checkBox", multiple: true}, "イヤリング", nil %><%= f.label 'check10', "イヤリング" %></li>
          <li><%= f.check_box :category, {id: "top_check14", class: "checkBox", multiple: true}, "ピアス", nil %><%= f.label 'check14', "ピアス" %></li>
          <li><%= f.check_box :category, {id: "top_check7", class: "checkBox", multiple: true}, "ブローチ", nil %><%= f.label 'check7', "ブローチ" %></li>
          <li><%= f.check_box :category, {id: "top_check9", class: "checkBox", multiple: true}, "バッグ", nil %><%= f.label 'check9', "バッグ" %></li>
          <li><%= f.check_box :category, {id: "top_check11", class: "checkBox", multiple: true}, "ポーチ", nil %><%= f.label 'check11', "ポーチ" %></li>
          <li><%= f.check_box :category, {id: "top_check2", class: "checkBox", multiple: true}, "財布", nil %><%= f.label 'check2', "財布" %></li>
          <li><%= f.check_box :category, {id: "top_check6", class: "checkBox", multiple: true}, "腕時計", nil %><%= f.label 'check6', "腕時計" %></li>
          <li><%= f.check_box :category, {id: "top_check13", class: "checkBox", multiple: true}, "雑貨", nil %><%= f.label 'check13', "雑貨" %></li>
        </dd>
      </dl>

      <h5 class="formLabel"><%= f.label "地域を入力してください" %></h5>
      <div id="textField"><%= f.text_field :area, :class => 'textField', :placeholder => "例）福岡市"%></div>
      <p class="areaWarning">※未入力の場合，現在地から検索します</p>
      <%= f.submit 'お店を再検索', :class => 'submitBtn'%>
    </div>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<% if request.from_smartphone? %>
  <%= render :partial => "searchResultMobile" %>
<% else %>
  <%= render :partial => "searchResult" %>
<% end %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<div id="main">
  <div id="shopDetail">
    <div id="shopInner">
      <% if request.from_smartphone? %>
        <%= render :partial => "shopInfoMobile" %>
      <% else %>
        <%= render :partial => "shopInfo" %>
      <% end %>
    </div>
  </div>
</div>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'access_canvas'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(17);
});
</script>

app/views/tops/_topForm.html.erb
<%= form_for "top", :url => shops_path do |f| %>
  <h1 class="formTitle">検索条件の入力</h1>
  <h5 class="formLabel"><%= f.label "買いたいものを選択してください" %><span class="areaWarning">*必須</span></h5>
  <dl id="categoryList">
    <!-- <dt><%= f.label "ファッション" %></dt> -->
    <dd>
      <li><%= f.check_box :category, {id: "top_check1", class: "checkBox", multiple: true}, "ネックレス", nil %><%= f.label 'check1', "ネックレス" %></li>
      <li><%= f.check_box :category, {id: "top_check5", class: "checkBox", multiple: true}, "ペンダント", nil %><%= f.label 'check5', "ペンダント" %></li>
      <li><%= f.check_box :category, {id: "top_check3", class: "checkBox", multiple: true}, "ブレスレット", nil %><%= f.label 'check3', "ブレスレット" %></li>
      <li><%= f.check_box :category, {id: "top_check4", class: "checkBox", multiple: true}, "指輪", nil %><%= f.label 'check4', "指輪" %></li>
      <li><%= f.check_box :category, {id: "top_check10", class: "checkBox", multiple: true}, "イヤリング", nil %><%= f.label 'check10', "イヤリング" %></li>
      <li><%= f.check_box :category, {id: "top_check14", class: "checkBox", multiple: true}, "ピアス", nil %><%= f.label 'check14', "ピアス" %></li>
      <li><%= f.check_box :category, {id: "top_check7", class: "checkBox", multiple: true}, "ブローチ", nil %><%= f.label 'check7', "ブローチ" %></li>
      <li><%= f.check_box :category, {id: "top_check9", class: "checkBox", multiple: true}, "バッグ", nil %><%= f.label 'check9', "バッグ" %></li>
      <li><%= f.check_box :category, {id: "top_check11", class: "checkBox", multiple: true}, "ポーチ", nil %><%= f.label 'check11', "ポーチ" %></li>
      <li><%= f.check_box :category, {id: "top_check2", class: "checkBox", multiple: true}, "財布", nil %><%= f.label 'check2', "財布" %></li>
      <li><%= f.check_box :category, {id: "top_check6", class: "checkBox", multiple: true}, "腕時計", nil %><%= f.label 'check6', "腕時計" %></li>
      <li><%= f.check_box :category, {id: "top_check13", class: "checkBox", multiple: true}, "雑貨", nil %><%= f.label 'check13', "雑貨" %></li>
    </dd>
  </dl>

  <h5 class="formLabel"><%= f.label "地域を入力してください" %></h5>
  <div id="textField"><%= f.text_field :area, :class => 'textField', :placeholder => "例）福岡市"%></div>
  <p class="areaWarning">※未入力の場合，現在地から検索します</p>
  <%= f.submit 'お店を検索', :class => 'submitBtn'%>
<% end %>

app/views/tops/_topFormMobile.html.erb
<%= form_for "top", :url => shops_path do |f| %>
  <h2 class="formTitle">検索条件の入力</h2>
  <h5 class="formLabel"><%= f.label "買いたいものを選択してください" %><span class="areaWarning">*必須</span></h5>
  <dl id="categoryList">
    <!-- <dt><%= f.label "ファッション" %></dt> -->
    <dd>
      <li><%= f.check_box :category, {id: "top_check1", class: "checkBox", multiple: true}, "ネックレス", nil %><%= f.label 'check1', "ネックレス" %></li>
      <li><%= f.check_box :category, {id: "top_check5", class: "checkBox", multiple: true}, "ペンダント", nil %><%= f.label 'check5', "ペンダント" %></li>
      <li><%= f.check_box :category, {id: "top_check3", class: "checkBox", multiple: true}, "ブレスレット", nil %><%= f.label 'check3', "ブレスレット" %></li>
      <li><%= f.check_box :category, {id: "top_check4", class: "checkBox", multiple: true}, "指輪", nil %><%= f.label 'check4', "指輪" %></li>
      <li><%= f.check_box :category, {id: "top_check10", class: "checkBox", multiple: true}, "イヤリング", nil %><%= f.label 'check10', "イヤリング" %></li>
      <li><%= f.check_box :category, {id: "top_check14", class: "checkBox", multiple: true}, "ピアス", nil %><%= f.label 'check14', "ピアス" %></li>
      <li><%= f.check_box :category, {id: "top_check7", class: "checkBox", multiple: true}, "ブローチ", nil %><%= f.label 'check7', "ブローチ" %></li>
      <li><%= f.check_box :category, {id: "top_check9", class: "checkBox", multiple: true}, "バッグ", nil %><%= f.label 'check9', "バッグ" %></li>
      <li><%= f.check_box :category, {id: "top_check11", class: "checkBox", multiple: true}, "ポーチ", nil %><%= f.label 'check11', "ポーチ" %></li>
      <li><%= f.check_box :category, {id: "top_check2", class: "checkBox", multiple: true}, "財布", nil %><%= f.label 'check2', "財布" %></li>
      <li><%= f.check_box :category, {id: "top_check6", class: "checkBox", multiple: true}, "腕時計", nil %><%= f.label 'check6', "腕時計" %></li>
      <li><%= f.check_box :category, {id: "top_check13", class: "checkBox", multiple: true}, "雑貨", nil %><%= f.label 'check13', "雑貨" %></li>
    </dd>
  </dl>

  <h5 class="formLabel"><%= f.label "地域を入力してください" %></h5>
  <div id="textField"><%= f.text_field :area, :class => 'textField', :placeholder => "例）福岡市"%></div>
  <p class="areaWarning"><font size="+2">※未入力の場合，現在地から検索します</font></p>
  <%= f.submit 'お店を検索', :class => 'submitBtn'%>
<% end %>